name: twodou_app
description: A simple Task Todo Application

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.1+1
  shared_preferences: ^2.0.15
  logging: ^1.0.2
  google_fonts: ^3.0.1
  provider: ^6.0.3
  equatable: ^2.0.3
  sqflite: ^2.0.3
  path_provider: ^2.0.11
  synchronized: ^3.0.0+2
  sqlbrite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true





  assets:
    - assets/images/


